name       : inih
version    : 52
release    : 1
source     :
    - https://github.com/benhoyt/inih/archive/r52.tar.gz : 439cff9ce9a8afc52d08772ac3e93b3cecd79c7707f871fb4534fb3a48201880
license    : BSD-3-Clause
component  : programming.library
summary    : inih (INI Not Invented Here) is a simple .INI file parser written in C
description: |
    inih (INI Not Invented Here) is a simple .INI file parser written in C.
setup      : |
    %meson_configure -Ddefault_library=shared -Ddistro_install=true -Dwith_INIReader=true
build      : |
    %ninja_build
install    : |
    %ninja_install
