name       : inih
version    : '53'
release    : 3
source     :
    - https://github.com/benhoyt/inih/archive/r53.tar.gz : 01b0366fdfdf6363efc070c2f856f1afa33e7a6546548bada5456ad94a516241
license    : BSD-3-Clause
component  : programming.library
summary    : inih (INI Not Invented Here) is a simple .INI file parser written in C
description: |
    inih (INI Not Invented Here) is a simple .INI file parser written in C.
emul32     : yes
setup      : |
    %meson_configure -Ddefault_library=shared -Ddistro_install=true -Dwith_INIReader=true
build      : |
    %ninja_build
install    : |
    %ninja_install
